In [19]:
import cv2
import numpy as np

### Open, View, and Save Image

In [2]:
img = cv2.imread('C:/Users/samue/Python Data/opencv-master/samples/data/lena.jpg', 0) #load image in grayscale
print(img)

cv2.imshow('image', img)
k = cv2.waitKey(0) & 0xFF #shows the window until close, provides mask

if k == 27: #escape key
    cv2.destroyAllWindows()
elif k == ord("s"): #if s key is pressed
    cv2.imwrite('lena_copy.png', img) #save image 
    cv2.destroyAllWindows()

[[163 162 161 ... 170 154 130]
 [162 162 162 ... 173 155 126]
 [162 162 163 ... 170 155 128]
 ...
 [ 43  42  51 ... 103 101  99]
 [ 41  42  55 ... 103 105 106]
 [ 42  44  57 ... 102 106 109]]


### Open, View, and Save Video

In [7]:
cap = cv2.VideoCapture(0) #device index, default webcam from device
fourcc = cv2.VideoWriter_fourcc(*"XVID") #fourcc code
out = cv2.VideoWriter('output.avi', fourcc, 30, (640, 480)) #30fps and size of video


while(cap.isOpened()): #while camera is open 
    ret, frame = cap.read() #capture and save frame from video 
    
    if ret == True:
    
        #print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        #print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        
        out.write(frame) #write frame to variable
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #change to grayscale image
        cv2.imshow('frame', gray)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
            
    else: 
        break
    
cap.release()
out.release() #convert to video
cv2.destroyAllWindows()

### Drawing Function

In [43]:
import numpy as np 

#img = cv2.imread('C:/Users/samue/Python Data/opencv-master/samples/data/lena.jpg', 1)

img = np.zeros([512, 512, 3]) #inside list is height, width, and 3 default for black image

img = cv2.line(img, (0,0), (255,255), (0,0, 255), 5) #draw a line through image using start and end coordinate tuples, color using BGR, and line thickness
img = cv2.arrowedLine(img, (0, 255), (255, 255), (255, 0, 0), 5)

img = cv2.rectangle(img, (380, 0), (510, 128), (0, 255, 0), -1) #top left and bottom right coordinates, negative fills in the shape
img = cv2.circle(img, (447, 64), 30, (32,102, 208), 5)
font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img, 'Hello!', (40, 500), font, 4, (255, 255, 255), 4, cv2.LINE_AA)

cv2.imshow('image', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Add Text to Video 

In [15]:
import datetime

cap = cv2.VideoCapture(0) #device index, default webcam from device
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

#cap.set(cv2.CAP_PROP_FRAME_WIDTH, 2000) #relies on camera resolution
#cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 2000)

#print(cap.get(3)) #3 and 4 are the cv properties for width and height
#print(cap.get(4))


while(cap.isOpened()): #while camera is open 
    ret, frame = cap.read() #capture and save frame from video 
    
    if ret == True:
        
        font = cv2.FONT_HERSHEY_SIMPLEX
        #text = 'Width: ' +  str(cap.get(3)) + ' Height: ' + str(cap.get(4))
        time = str(datetime.datetime.now())
        frame = cv2.putText(frame, time, (10, 50), font, 1, (0, 255, 255), 2, cv2.LINE_AA)
        cv2.imshow('frame', frame)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
            
    else: 
        break
    
cap.release()
cv2.destroyAllWindows()

640.0
480.0


### Handle Mouse Events

In [16]:
events = [i for i in dir(cv2) if 'EVENT' in i]
events

['EVENT_FLAG_ALTKEY',
 'EVENT_FLAG_CTRLKEY',
 'EVENT_FLAG_LBUTTON',
 'EVENT_FLAG_MBUTTON',
 'EVENT_FLAG_RBUTTON',
 'EVENT_FLAG_SHIFTKEY',
 'EVENT_LBUTTONDBLCLK',
 'EVENT_LBUTTONDOWN',
 'EVENT_LBUTTONUP',
 'EVENT_MBUTTONDBLCLK',
 'EVENT_MBUTTONDOWN',
 'EVENT_MBUTTONUP',
 'EVENT_MOUSEHWHEEL',
 'EVENT_MOUSEMOVE',
 'EVENT_MOUSEWHEEL',
 'EVENT_RBUTTONDBLCLK',
 'EVENT_RBUTTONDOWN',
 'EVENT_RBUTTONUP']

In [26]:
def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x, ", ", y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ', ' + str(y)
        cv2.putText(img, strXY, (x, y), font, 0.5, (255, 255, 0), 1)
        cv2.imshow('image', img)
    
    if event == cv2.EVENT_RBUTTONDOWN: #show bgr channel for location clickedq
        blue = img[y, x, 0] #0 is channel for blue color
        green = img[y, x, 1] 
        red = img[y, x, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        bgr = str(blue) + ', ' + str(green) + ', ' + str(red)
        cv2.putText(img, bgr, (x, y), font, 0.5, (0, 255, 255, 1)
        cv2.imshow('image', img)

In [28]:
#img = np.zeros((512, 512, 3), np.uint8)
img = cv2.imread('C:/Users/samue/Python Data/opencv-master/samples/data/lena.jpg', 1)

cv2.imshow('image', img)

cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

89 ,  63
